### ISSUE TITLE
How can I use my picture to test GVRT?

### ISSUE THREAD

**Issue by Espere-1119-Song** [mswzeus/GVRT#1]

**Comment by seonwoo-min** [comment]
@Espere-1119-Song, Thank you for your interest in our work.
Currently, the repo does not support evaluations with other datasets.
In order to use your pictures to test the pre-trained models, you will need to create a custom dataset class.
Please refer to the CUB_DG_Dataset class for creating a custom dataset class.
https://github.com/mswzeus/GVRT/blob/6ecb2b8e069787933dda72bb61e33f956b586d6f/src/data.py#L19-L63

**Comment by Espere-1119-Song** [comment]
Thanks a lot~
