### ISSUE TITLE
A question about dataset

### ISSUE THREAD

**Issue by ZhenyuLiu-SYSU** [mswzeus/GVRT#5]
Dear author：

I'm glad to see your excellent work.
As I'm a newcomer to the DG field,  when I open the CUB-DG dataset, I found that these were some .npy files and a .pkl file.
![image](https://user-images.githubusercontent.com/74093654/229718537-bb98d346-728a-4417-8965-1e0375641d19.png)

I would like to ask What are the functions of these files and how should they be generated?
I would appreciate it if you could reply！

**Comment by seonwoo-min** [comment]
Hi @ZhenyuLiu-SYSU,

They are pre-processed data files of CUB-DG text descriptions.
texts_s.npy file contains sentence-level text embeddings obtained from the pre-trained textual encoder, CLIP-ViT-B-32.
The other files contain sequences of word tokens, their lengths, and word vocabulary obtained from the PTBTokenizer.
Note that currently, we provide the pre-processed data files instead of the script for generating them.

The CUB_DG_Dataset class uses pre-processed data files instead of raw texts for more efficient data loading.
https://github.com/mswzeus/GVRT/blob/6ecb2b8e069787933dda72bb61e33f956b586d6f/src/data.py#L19-L63

**Comment by ZhenyuLiu-SYSU** [comment]
I understand, 
so what do I should to do if I want to generate these pre-processed data files on other datasets

**Comment by seonwoo-min** [comment]
@ZhenyuLiu-SYSU, It's a great point!
I have uploaded the pre-processing script for texts as well.
Assuming that other datasets have the same file organization as CUB-DG, you can use the <code>preprocess_texts.py</code> as:
```
CUDA_VISIBLE_DEVICES=0 python preproces_texts.py data/CUB-DG
```
Note that the <code>requirements.txt</code> file has also been updated for the preprocessing script.

**Comment by ZhenyuLiu-SYSU** [comment]
Thanks for your reply!
I will try it.
